# Generated by Django 5.1.7 on 2025-04-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('hr', 'HR'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
