# Generated by Django 5.1.3 on 2025-03-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_list',
            new_name='Job',
        ),
    ]
