# Generated by Django 5.1.7 on 2025-04-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
