# Generated by Django 5.1.7 on 2025-04-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_of_posting'], 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/%Y/%m/%d/'),
        ),
    ]
